services:
  workspace:
    build: .
    command: sleep infinity
    volumes:
      - code:/workspace
    working_dir: /workspace
    environment:
      - GITEA_WORK_DIR=/workspace
      - TAGS=bindata sqlite sqlite_unlock_notify

  dev:
    build: .
    command: make watch
    user: "1000:1000"
    ports:
      - "3000"
    volumes:
      - code:/workspace
    working_dir: /workspace
    environment:
      - GITEA_WORK_DIR=/workspace
      - TAGS=bindata sqlite sqlite_unlock_notify
      - GITEA_RUN_MODE=dev
      - GITEA__server__HTTP_ADDR=0.0.0.0
      - HOME=/home/gitea
      - GOPATH=/home/gitea/go

volumes:
  code:
    external: true
    name: bl-f44b-code
