services:
  workspace:
    build: .
    command: sleep infinity
    volumes:
      - code:/workspace
    working_dir: /workspace
    depends_on:
      - postgres
      - redis
      - inbucket
      - minio
    environment:
      - NEXTAUTH_SECRET=secret
      - NEXT_PRIVATE_ENCRYPTION_KEY=CAFEBABE0123456789ABCDEF01234567
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=DEADBEEF0123456789ABCDEF01234567
      - NEXT_PUBLIC_WEBAPP_URL=http://dev:3000
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=http://dev:3000
      - NEXT_PRIVATE_DATABASE_URL=postgres://documenso:password@postgres:5432/documenso
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=postgres://documenso:password@postgres:5432/documenso
      - NEXT_PRIVATE_SIGNING_TRANSPORT=local
      - NEXT_PRIVATE_JOBS_PROVIDER=local
      - NEXT_PRIVATE_REDIS_URL=redis://redis:6379
      - NEXT_PRIVATE_REDIS_PREFIX=documenso
      - NEXT_PRIVATE_SMTP_TRANSPORT=smtp-auth
      - NEXT_PRIVATE_SMTP_HOST=inbucket
      - NEXT_PRIVATE_SMTP_PORT=2500
      - NEXT_PRIVATE_SMTP_USERNAME=documenso
      - NEXT_PRIVATE_SMTP_PASSWORD=password
      - NEXT_PRIVATE_SMTP_FROM_NAME=Documenso
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=noreply@documenso.com
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=s3
      - NEXT_PRIVATE_UPLOAD_ENDPOINT=http://minio:9002
      - NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=true
      - NEXT_PRIVATE_UPLOAD_REGION=us-east-1
      - NEXT_PRIVATE_UPLOAD_BUCKET=documenso
      - NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=documenso
      - NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=password
      - PORT=3000

  dev:
    build: .
    command: npx turbo run dev --filter=@documenso/remix -- --host 0.0.0.0
    ports:
      - "3000"
    volumes:
      - code:/workspace
    working_dir: /workspace
    depends_on:
      - postgres
      - redis
      - inbucket
      - minio
    environment:
      - NEXTAUTH_SECRET=secret
      - NEXT_PRIVATE_ENCRYPTION_KEY=CAFEBABE0123456789ABCDEF01234567
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=DEADBEEF0123456789ABCDEF01234567
      - NEXT_PUBLIC_WEBAPP_URL=http://dev:3000
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=http://dev:3000
      - NEXT_PRIVATE_DATABASE_URL=postgres://documenso:password@postgres:5432/documenso
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=postgres://documenso:password@postgres:5432/documenso
      - NEXT_PRIVATE_SIGNING_TRANSPORT=local
      - NEXT_PRIVATE_JOBS_PROVIDER=local
      - NEXT_PRIVATE_REDIS_URL=redis://redis:6379
      - NEXT_PRIVATE_REDIS_PREFIX=documenso
      - NEXT_PRIVATE_SMTP_TRANSPORT=smtp-auth
      - NEXT_PRIVATE_SMTP_HOST=inbucket
      - NEXT_PRIVATE_SMTP_PORT=2500
      - NEXT_PRIVATE_SMTP_USERNAME=documenso
      - NEXT_PRIVATE_SMTP_PASSWORD=password
      - NEXT_PRIVATE_SMTP_FROM_NAME=Documenso
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=noreply@documenso.com
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=s3
      - NEXT_PRIVATE_UPLOAD_ENDPOINT=http://minio:9002
      - NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=true
      - NEXT_PRIVATE_UPLOAD_REGION=us-east-1
      - NEXT_PRIVATE_UPLOAD_BUCKET=documenso
      - NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=documenso
      - NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=password
      - PORT=3000
      - HOST=0.0.0.0

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=documenso
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=documenso
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  inbucket:
    image: inbucket/inbucket
    ports:
      - "9000"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: documenso
      MINIO_ROOT_PASSWORD: password
    entrypoint: sh
    command: -c 'mkdir -p /data/documenso && minio server /data --console-address ":9001" --address ":9002"'
    volumes:
      - minio-data:/data

volumes:
  code:
    external: true
    name: bl-6e79-code
  postgres-data:
  minio-data:
