{
  "services": {
    "dev": {
      "build": ".",
      "command": "mix boom.server",
      "environment": [
        "MIX_ENV=dev",
        "PORT=4000",
        "BOOMLOOPER_HOME=/workspace/.boomlooper_home"
      ],
      "ports": [
        "127.0.0.1::4000"
      ],
      "volumes": [
        "code:/workspace"
      ],
      "working_dir": "/workspace"
    },
    "workspace": {
      "build": ".",
      "command": "sleep infinity",
      "environment": [
        "MIX_ENV=dev",
        "PORT=4000",
        "BOOMLOOPER_HOME=/workspace/.boomlooper_home"
      ],
      "volumes": [
        "code:/workspace"
      ],
      "working_dir": "/workspace"
    }
  },
  "volumes": {
    "bl-81e3-code": {
      "external": true
    },
    "code": {
      "external": true,
      "name": "bl-81e3-code"
    }
  }
}