{
  "services": {
    "dev": {
      "build": {
        "context": "/Users/bradgessler/Projects/boomlooper/boomlooper/.hive",
        "dockerfile": "Dockerfile"
      },
      "command": "mix phx.server",
      "environment": [
        "MIX_ENV=dev",
        "PHX_HOST=localhost",
        "PORT=4000"
      ],
      "ports": [
        "4000:4000"
      ],
      "volumes": [
        "/Users/bradgessler/Projects/boomlooper/boomlooper:/workspace",
        "cache-boomlooper:/root/.cache"
      ],
      "working_dir": "/workspace"
    },
    "workspace": {
      "build": {
        "context": "/Users/bradgessler/Projects/boomlooper/boomlooper/.hive",
        "dockerfile": "Dockerfile"
      },
      "command": "sleep infinity",
      "environment": [
        "MIX_ENV=dev",
        "PHX_HOST=localhost",
        "PORT=4000"
      ],
      "volumes": [
        "/Users/bradgessler/Projects/boomlooper/boomlooper:/workspace",
        "cache-boomlooper:/root/.cache"
      ],
      "working_dir": "/workspace"
    }
  },
  "volumes": {
    "cache-boomlooper": null
  }
}
