{
  "services": {
    "dev": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile",
        "target": "dev"
      },
      "command": "bash -c \"bundle install && npm install && bin/rails server -b 0.0.0.0 -p 3000\"\n",
      "depends_on": {
        "postgres": {
          "condition": "service_healthy"
        },
        "redis": {
          "condition": "service_healthy"
        }
      },
      "environment": {
        "BINDING": "0.0.0.0",
        "DATABASE_URL": "postgis://postgres@postgres:5432/garryslist_development",
        "PGHOST": "postgres",
        "PGUSER": "postgres",
        "QUEUE_DATABASE_URL": "postgis://postgres@postgres:5432/garryslist_development_queue",
        "RAILS_ENV": "development",
        "REDIS_URL": "redis://redis:6379/0"
      },
      "ports": [
        "127.0.0.1:32866:3000"
      ],
      "volumes": [
        "bl-faa5-code:/workspace",
        "bundle_cache:/usr/local/bundle",
        "node_modules:/workspace/node_modules"
      ],
      "working_dir": "/workspace"
    },
    "postgres": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile",
        "target": "postgres"
      },
      "environment": {
        "POSTGRES_HOST_AUTH_METHOD": "trust",
        "POSTGRES_USER": "postgres"
      },
      "healthcheck": {
        "interval": "3s",
        "retries": 10,
        "test": [
          "CMD-SHELL",
          "pg_isready -U postgres"
        ],
        "timeout": "3s"
      },
      "ports": [
        "127.0.0.1:32860:5432"
      ],
      "volumes": [
        "pgdata:/var/lib/postgresql/data"
      ]
    },
    "redis": {
      "healthcheck": {
        "interval": "3s",
        "retries": 10,
        "test": [
          "CMD",
          "redis-cli",
          "ping"
        ],
        "timeout": "3s"
      },
      "image": "redis:7-alpine",
      "ports": [
        "127.0.0.1:32859:6379"
      ]
    }
  },
  "volumes": {
    "bl-faa5-code": {
      "external": true
    },
    "bundle_cache": null,
    "node_modules": null,
    "pgdata": null
  }
}