services:
  workspace:
    build: .
    command: sleep infinity
    volumes:
      - code:/workspace
    working_dir: /workspace
    environment:
      - MIX_ENV=dev

  dev:
    build: .
    command: mix boom.server
    ports:
      - "4000"
    volumes:
      - code:/workspace
    working_dir: /workspace
    environment:
      - MIX_ENV=dev
      - PHX_HOST=0.0.0.0

volumes:
  code:
    external: true
    name: code-b6bd
