services:
  workspace:
    build: .
    command: sleep infinity
    volumes:
      - code:/workspace
    working_dir: /workspace
    environment:
      - DB=postgres
      - DATABASE_HOST=postgres
    depends_on:
      - postgres

  dev:
    build: .
    command: yarn develop
    working_dir: /workspace/examples/getstarted
    ports:
      - "1337"
    volumes:
      - code:/workspace
    environment:
      - DB=postgres
      - DATABASE_HOST=postgres
      - HOST=0.0.0.0
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
      - POSTGRES_DB=strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  code:
    external: true
    name: bl-e437-code
  postgres-data:
