services:
  workspace:
    build: .
    command: sleep infinity
    volumes:
      - code:/workspace
    working_dir: /workspace
    depends_on:
      - db
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bookstack-dev
      - DB_USERNAME=bookstack-test
      - DB_PASSWORD=bookstack-test
      - MAIL_DRIVER=log

  dev:
    build: .
    command: apache2-foreground
    ports:
      - "80"
    volumes:
      - code:/workspace
    working_dir: /workspace
    depends_on:
      - db
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - APACHE_DOCUMENT_ROOT=/workspace/public
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bookstack-dev
      - DB_USERNAME=bookstack-test
      - DB_PASSWORD=bookstack-test
      - MAIL_DRIVER=log

  node:
    image: node:22-alpine
    command: sh -c "npm install && npm run watch"
    volumes:
      - code:/workspace
    working_dir: /workspace

  db:
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=bookstack-dev
      - MYSQL_USER=bookstack-test
      - MYSQL_PASSWORD=bookstack-test
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - db-data:/var/lib/mysql

volumes:
  code:
    external: true
    name: bl-76d9-code
  db-data:
