{
  "services": {
    "css": {
      "build": ".",
      "command": "tailwind-watch",
      "restart": "unless-stopped",
      "volumes": [
        "code:/workspace",
        "bundle:/usr/local/bundle"
      ],
      "working_dir": "/workspace"
    },
    "dev": {
      "build": ".",
      "command": "bin/rails server -b 0.0.0.0 -p 3000",
      "environment": [
        "BINDING=0.0.0.0",
        "PORT=3000"
      ],
      "ports": [
        "127.0.0.1::3000"
      ],
      "volumes": [
        "code:/workspace",
        "bundle:/usr/local/bundle"
      ],
      "working_dir": "/workspace"
    },
    "workspace": {
      "build": ".",
      "command": "sleep infinity",
      "volumes": [
        "code:/workspace",
        "bundle:/usr/local/bundle"
      ],
      "working_dir": "/workspace"
    }
  },
  "volumes": {
    "bl-a866-code": {
      "external": true
    },
    "bundle": null,
    "code": {
      "external": true,
      "name": "bl-a866-code"
    }
  }
}