{
  "services": {
    "dev": {
      "build": ".",
      "command": "./gitea web --port 3000",
      "environment": [
        "HOME=/home/gitea",
        "GITEA_WORK_DIR=/workspace",
        "GITEA_CUSTOM=/workspace/custom"
      ],
      "ports": [
        "127.0.0.1:4006:3000"
      ],
      "user": "1000:1000",
      "volumes": [
        "code:/workspace"
      ],
      "working_dir": "/workspace"
    },
    "workspace": {
      "build": ".",
      "command": "sleep infinity",
      "environment": [
        "GITEA_WORK_DIR=/workspace",
        "GOFLAGS=-buildvcs=false"
      ],
      "volumes": [
        "code:/workspace"
      ],
      "working_dir": "/workspace"
    }
  },
  "volumes": {
    "bl-7422-code": {
      "external": true
    },
    "code": {
      "external": true,
      "name": "bl-7422-code"
    }
  }
}