{
  "services": {
    "dev": {
      "build": ".",
      "command": "bin/ember-cli -u --host 0.0.0.0",
      "depends_on": [
        "postgres",
        "redis"
      ],
      "environment": {
        "BINDING": "0.0.0.0",
        "BUNDLE_PATH": "/usr/local/bundle",
        "DATABASE_URL": "postgres://postgres@postgres:5432/discourse_development",
        "DISABLE_SPRING": "1",
        "DISCOURSE_DB_HOST": "postgres",
        "DISCOURSE_DB_NAME": "discourse_development",
        "DISCOURSE_DB_USERNAME": "postgres",
        "DISCOURSE_DEV_DB": "discourse_development",
        "DISCOURSE_HOSTNAME": "localhost",
        "DISCOURSE_PORT": "4200",
        "DISCOURSE_REDIS_HOST": "redis",
        "RAILS_ENV": "development",
        "REDIS_URL": "redis://redis:6379/0",
        "UNICORN_BIND_ALL": "1",
        "UNICORN_PORT": "3000"
      },
      "ports": [
        "127.0.0.1:4007:4200"
      ],
      "volumes": [
        "code:/workspace",
        "bundle:/usr/local/bundle"
      ],
      "working_dir": "/workspace"
    },
    "postgres": {
      "environment": {
        "POSTGRES_HOST_AUTH_METHOD": "trust"
      },
      "image": "pgvector/pgvector:pg16",
      "volumes": [
        "postgres-data:/var/lib/postgresql/data"
      ]
    },
    "redis": {
      "image": "redis:7-alpine"
    },
    "workspace": {
      "build": ".",
      "command": "sleep infinity",
      "environment": {
        "BINDING": "0.0.0.0",
        "BUNDLE_PATH": "/usr/local/bundle",
        "DATABASE_URL": "postgres://postgres@postgres:5432/discourse_development",
        "DISABLE_SPRING": "1",
        "DISCOURSE_DB_HOST": "postgres",
        "DISCOURSE_DB_NAME": "discourse_development",
        "DISCOURSE_DB_USERNAME": "postgres",
        "DISCOURSE_DEV_DB": "discourse_development",
        "DISCOURSE_HOSTNAME": "localhost",
        "DISCOURSE_PORT": "4200",
        "DISCOURSE_REDIS_HOST": "redis",
        "RAILS_ENV": "development",
        "REDIS_URL": "redis://redis:6379/0",
        "UNICORN_BIND_ALL": "1",
        "UNICORN_PORT": "3000"
      },
      "volumes": [
        "code:/workspace",
        "bundle:/usr/local/bundle"
      ],
      "working_dir": "/workspace"
    }
  },
  "volumes": {
    "bl-9c58-code": {
      "external": true
    },
    "bundle": null,
    "code": {
      "external": true,
      "name": "bl-9c58-code"
    },
    "postgres-data": null
  },
  "x-app-env": {
    "BINDING": "0.0.0.0",
    "BUNDLE_PATH": "/usr/local/bundle",
    "DATABASE_URL": "postgres://postgres@postgres:5432/discourse_development",
    "DISABLE_SPRING": "1",
    "DISCOURSE_DB_HOST": "postgres",
    "DISCOURSE_DB_NAME": "discourse_development",
    "DISCOURSE_DB_USERNAME": "postgres",
    "DISCOURSE_DEV_DB": "discourse_development",
    "DISCOURSE_HOSTNAME": "localhost",
    "DISCOURSE_PORT": "4200",
    "DISCOURSE_REDIS_HOST": "redis",
    "RAILS_ENV": "development",
    "REDIS_URL": "redis://redis:6379/0",
    "UNICORN_BIND_ALL": "1",
    "UNICORN_PORT": "3000"
  }
}